// <auto-generated />
using Herbalist.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Herbalist.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190820114948_LocationEnum")]
    partial class LocationEnum
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Herbalist.Models.HerbInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DC");

                    b.Property<string>("HerbName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("Location");

                    b.Property<int>("Rarity");

                    b.HasKey("Id");

                    b.ToTable("HerbInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
