// <auto-generated />
using System;
using Herbalist.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Herbalist.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Herbalist.Models.HerbAmount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount");

                    b.Property<int>("HerbId");

                    b.Property<int>("PotionId");

                    b.HasKey("Id");

                    b.ToTable("Herbs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 5,
                            HerbId = -1,
                            PotionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 3,
                            HerbId = 9,
                            PotionId = 2
                        },
                        new
                        {
                            Id = 3,
                            Amount = 6,
                            HerbId = -2,
                            PotionId = 3
                        },
                        new
                        {
                            Id = 4,
                            Amount = 3,
                            HerbId = 1,
                            PotionId = 4
                        },
                        new
                        {
                            Id = 5,
                            Amount = 1,
                            HerbId = 7,
                            PotionId = 4
                        },
                        new
                        {
                            Id = 6,
                            Amount = 2,
                            HerbId = 10,
                            PotionId = 5
                        },
                        new
                        {
                            Id = 7,
                            Amount = 10,
                            HerbId = 3,
                            PotionId = 6
                        },
                        new
                        {
                            Id = 8,
                            Amount = 5,
                            HerbId = 15,
                            PotionId = 7
                        },
                        new
                        {
                            Id = 9,
                            Amount = 3,
                            HerbId = 15,
                            PotionId = 8
                        },
                        new
                        {
                            Id = 10,
                            Amount = 5,
                            HerbId = -2,
                            PotionId = 8
                        },
                        new
                        {
                            Id = 11,
                            Amount = 10,
                            HerbId = -2,
                            PotionId = 9
                        },
                        new
                        {
                            Id = 12,
                            Amount = 10,
                            HerbId = 2,
                            PotionId = 10
                        },
                        new
                        {
                            Id = 13,
                            Amount = 10,
                            HerbId = 6,
                            PotionId = 11
                        },
                        new
                        {
                            Id = 14,
                            Amount = 10,
                            HerbId = 10,
                            PotionId = 12
                        },
                        new
                        {
                            Id = 15,
                            Amount = 10,
                            HerbId = 14,
                            PotionId = 13
                        },
                        new
                        {
                            Id = 16,
                            Amount = 10,
                            HerbId = 18,
                            PotionId = 14
                        },
                        new
                        {
                            Id = 17,
                            Amount = 5,
                            HerbId = 18,
                            PotionId = 15
                        },
                        new
                        {
                            Id = 18,
                            Amount = 5,
                            HerbId = 19,
                            PotionId = 15
                        },
                        new
                        {
                            Id = 19,
                            Amount = 10,
                            HerbId = 17,
                            PotionId = 16
                        },
                        new
                        {
                            Id = 20,
                            Amount = 10,
                            HerbId = 13,
                            PotionId = 16
                        },
                        new
                        {
                            Id = 21,
                            Amount = 7,
                            HerbId = -3,
                            PotionId = 17
                        },
                        new
                        {
                            Id = 22,
                            Amount = 4,
                            HerbId = -2,
                            PotionId = 18
                        },
                        new
                        {
                            Id = 23,
                            Amount = 4,
                            HerbId = -3,
                            PotionId = 18
                        },
                        new
                        {
                            Id = 24,
                            Amount = 3,
                            HerbId = 19,
                            PotionId = 19
                        },
                        new
                        {
                            Id = 25,
                            Amount = 5,
                            HerbId = 11,
                            PotionId = 20
                        },
                        new
                        {
                            Id = 26,
                            Amount = 1,
                            HerbId = 16,
                            PotionId = 21
                        },
                        new
                        {
                            Id = 27,
                            Amount = 3,
                            HerbId = 15,
                            PotionId = 21
                        },
                        new
                        {
                            Id = 28,
                            Amount = 4,
                            HerbId = 10,
                            PotionId = 22
                        },
                        new
                        {
                            Id = 29,
                            Amount = 4,
                            HerbId = 18,
                            PotionId = 22
                        },
                        new
                        {
                            Id = 30,
                            Amount = 2,
                            HerbId = 12,
                            PotionId = 23
                        },
                        new
                        {
                            Id = 31,
                            Amount = 2,
                            HerbId = 8,
                            PotionId = 23
                        },
                        new
                        {
                            Id = 32,
                            Amount = 2,
                            HerbId = 4,
                            PotionId = 23
                        },
                        new
                        {
                            Id = 33,
                            Amount = 3,
                            HerbId = 20,
                            PotionId = 24
                        },
                        new
                        {
                            Id = 34,
                            Amount = 3,
                            HerbId = 12,
                            PotionId = 24
                        },
                        new
                        {
                            Id = 35,
                            Amount = 1,
                            HerbId = 3,
                            PotionId = 25
                        },
                        new
                        {
                            Id = 36,
                            Amount = 1,
                            HerbId = 7,
                            PotionId = 25
                        },
                        new
                        {
                            Id = 37,
                            Amount = 1,
                            HerbId = 11,
                            PotionId = 25
                        },
                        new
                        {
                            Id = 38,
                            Amount = 1,
                            HerbId = 15,
                            PotionId = 25
                        },
                        new
                        {
                            Id = 39,
                            Amount = 1,
                            HerbId = 19,
                            PotionId = 25
                        },
                        new
                        {
                            Id = 40,
                            Amount = 10,
                            HerbId = 14,
                            PotionId = 26
                        },
                        new
                        {
                            Id = 41,
                            Amount = 2,
                            HerbId = 16,
                            PotionId = 26
                        },
                        new
                        {
                            Id = 42,
                            Amount = 2,
                            HerbId = 16,
                            PotionId = 27
                        },
                        new
                        {
                            Id = 43,
                            Amount = 3,
                            HerbId = 20,
                            PotionId = 27
                        },
                        new
                        {
                            Id = 44,
                            Amount = 6,
                            HerbId = -3,
                            PotionId = 28
                        },
                        new
                        {
                            Id = 45,
                            Amount = 4,
                            HerbId = -4,
                            PotionId = 28
                        },
                        new
                        {
                            Id = 46,
                            Amount = 10,
                            HerbId = -4,
                            PotionId = 29
                        },
                        new
                        {
                            Id = 47,
                            Amount = 10,
                            HerbId = 12,
                            PotionId = 30
                        },
                        new
                        {
                            Id = 48,
                            Amount = 6,
                            HerbId = 12,
                            PotionId = 31
                        },
                        new
                        {
                            Id = 49,
                            Amount = 10,
                            HerbId = 7,
                            PotionId = 31
                        },
                        new
                        {
                            Id = 50,
                            Amount = 9,
                            HerbId = 16,
                            PotionId = 32
                        },
                        new
                        {
                            Id = 51,
                            Amount = 2,
                            HerbId = 4,
                            PotionId = 33
                        },
                        new
                        {
                            Id = 52,
                            Amount = 2,
                            HerbId = 8,
                            PotionId = 33
                        },
                        new
                        {
                            Id = 53,
                            Amount = 2,
                            HerbId = 12,
                            PotionId = 33
                        },
                        new
                        {
                            Id = 54,
                            Amount = 2,
                            HerbId = 20,
                            PotionId = 33
                        },
                        new
                        {
                            Id = 55,
                            Amount = 10,
                            HerbId = 3,
                            PotionId = 34
                        },
                        new
                        {
                            Id = 56,
                            Amount = 10,
                            HerbId = 7,
                            PotionId = 34
                        },
                        new
                        {
                            Id = 57,
                            Amount = 10,
                            HerbId = 19,
                            PotionId = 34
                        },
                        new
                        {
                            Id = 58,
                            Amount = 9,
                            HerbId = 8,
                            PotionId = 35
                        },
                        new
                        {
                            Id = 59,
                            Amount = 9,
                            HerbId = 12,
                            PotionId = 35
                        },
                        new
                        {
                            Id = 60,
                            Amount = 12,
                            HerbId = 20,
                            PotionId = 36
                        },
                        new
                        {
                            Id = 61,
                            Amount = 12,
                            HerbId = 12,
                            PotionId = 36
                        });
                });

            modelBuilder.Entity("Herbalist.Models.HerbCount", b =>
                {
                    b.Property<int>("HerbId");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.Property<int>("Count");

                    b.HasKey("HerbId", "UserName");

                    b.ToTable("HerbCounts");
                });

            modelBuilder.Entity("Herbalist.Models.HerbInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DC");

                    b.Property<string>("HerbName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("Location");

                    b.Property<int>("Rarity");

                    b.HasKey("Id");

                    b.ToTable("HerbInfos");
                });

            modelBuilder.Entity("Herbalist.Models.PotionRecipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DC");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000);

                    b.Property<string>("PotionName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("Rarity");

                    b.HasKey("Id");

                    b.ToTable("PotionRecipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DC = 10,
                            Description = @"You regain 2d4 + 2 Hit Points when you drink this potion.
The potion's red liquid glimmers when agitated.",
                            PotionName = "Healing Potion",
                            Rarity = 0
                        },
                        new
                        {
                            Id = 2,
                            DC = 10,
                            Description = @"When you drink this potion, you gain a climbing speed equal to your walking speed for 1 hour. During this time, you have advantage on Strength (Athletics) checks you make to climb. 
The potion is separated into brown, silver, and gray layers resembling bands of stone. Shaking the bottle fails to mix the colors.",
                            PotionName = "Potion of Climbing",
                            Rarity = 0
                        },
                        new
                        {
                            Id = 3,
                            DC = 13,
                            Description = @"You regain 4d4 + 4 Hit Points when you drink this potion. 
The potion's red liquid glimmers when agitated.",
                            PotionName = "Greater Healing Potion",
                            Rarity = 1
                        },
                        new
                        {
                            Id = 4,
                            DC = 13,
                            Description = @"When you drink this potion, you can cast the Animal Friendship spell (save DC 13) for 1 hour at will. 
Agitating this muddy liquid brings little bits into view: a fish scale, a hummingbird tongue, a cat claw, or a squirrel hair.",
                            PotionName = "Potion of Animal Friendship",
                            Rarity = 1
                        },
                        new
                        {
                            Id = 5,
                            DC = 13,
                            Description = @"After drinking this potion, you can use a bonus action to exhale fire at a target within 30 feet of you. The target must make a DC 13 Dexterity saving throw, taking 4d6 fire damage on a failed save, or half as much damage on a successful one. The effect ends after you exhale the fire three times or when 1 hour has passed. 
This potion's orange liquid flickers, and smoke fills the top of the container and wafts out whenever it is opened. ",
                            PotionName = "Potion of Fire Breath",
                            Rarity = 1
                        },
                        new
                        {
                            Id = 6,
                            DC = 14,
                            Description = @"When you drink this potion, your Strength score changes to 21 for 1 hour. The potion has no effect on you if your Strength is equal to or greater than that score.
This potion's transparent liquid has floating in it a sliver of fingernail from a hill giant.",
                            PotionName = "Potion of Giant Strength (Hill Giant)",
                            Rarity = 1
                        },
                        new
                        {
                            Id = 7,
                            DC = 13,
                            Description = @"When you drink this potion, you gain the ""enlarge"" effect of the enlarge/reduce spell for 1d4 hours (no Concentration required).
The red in the potion's liquid continuously expands from a tiny bead to color the clear liquid around it and then contracts. Shaking the bottle fails to interrupt this process.",
                            PotionName = "Potion of Growth",
                            Rarity = 1
                        },
                        new
                        {
                            Id = 8,
                            DC = 14,
                            Description = @"This concoction looks, smells, and tastes like a Potion of Healing or other beneficial potion. However, it is actually poison masked by Illusion magic. An Identify spell reveals its true Nature.
If you drink it, you take 3d6 poison damage, and you must succeed on a DC 13 Constitution saving throw or be Poisoned. At the start of each of your turns while you are Poisoned in this way, you take 3d6 poison damage. At the end of each of your turns, you can repeat the saving throw.On a successful save, the poison damage you take on your subsequent turns decreases by 1d6.The poison ends when the damage decreases to 0.",
                            PotionName = "Potion of Poison",
                            Rarity = 1
                        },
                        new
                        {
                            Id = 9,
                            DC = 14,
                            Description = "When you drink this potion, you gain resistance to one type of damage for 1 hour. The DM chooses the type or determines it randomly.",
                            PotionName = "Potion of Resistance (Random resistance)",
                            Rarity = 1
                        },
                        new
                        {
                            Id = 10,
                            DC = 14,
                            Description = "When you drink this potion, you gain resistance to Force and Radiant damage for 1 hour.",
                            PotionName = "Potion of Resistance (Force, Radiant)",
                            Rarity = 1
                        },
                        new
                        {
                            Id = 11,
                            DC = 14,
                            Description = "When you drink this potion, you gain resistance to Cold and Necrotic damage for 1 hour.",
                            PotionName = "Potion of Resistance (Cold, Necrotic)",
                            Rarity = 1
                        },
                        new
                        {
                            Id = 12,
                            DC = 14,
                            Description = "When you drink this potion, you gain resistance to Fire and Psychic damage for 1 hour.",
                            PotionName = "Potion of Resistance (Fire, Psychic)",
                            Rarity = 1
                        },
                        new
                        {
                            Id = 13,
                            DC = 14,
                            Description = "When you drink this potion, you gain resistance to Acid and Poison damage for 1 hour.",
                            PotionName = "Potion of Resistance (Acid, Poison)",
                            Rarity = 1
                        },
                        new
                        {
                            Id = 14,
                            DC = 14,
                            Description = "When you drink this potion, you gain resistance to Lightning and Thunder damage for 1 hour.",
                            PotionName = "Potion of Resistance (Lightning, Thunder)",
                            Rarity = 1
                        },
                        new
                        {
                            Id = 15,
                            DC = 13,
                            Description = @"You can breathe Underwater for 1 hour after drinking this potion.
Its cloudy green fluid smells of the sea and has a jellyfish-like bubble floating in it.",
                            PotionName = "Potion of Water Breathing",
                            Rarity = 1
                        },
                        new
                        {
                            Id = 16,
                            DC = 13,
                            Description = @"This sticky black unguent is thick and heavy in the container, but it flows quickly when poured.
The oil can cover a Medium or smaller creature, along with the Equipment it's wearing and carrying (one additional vial is required for each size category above Medium). Applying the oil takes 10 minutes. The affected creature then gains the effect of a Freedom of Movement spell for 8 hours. Alternatively, the oil can be poured on the ground as an action, where it covers a 10 - foot square, duplicating the effect of the Grease spell in that area for 8 hours.",
                            PotionName = "Oil of Slipperiness",
                            Rarity = 1
                        },
                        new
                        {
                            Id = 17,
                            DC = 16,
                            Description = @"You regain 8d4 + 8 Hit Points when you drink this potion. 
The potion's red liquid glimmers when agitated.",
                            PotionName = "Superior Healing Potion",
                            Rarity = 2
                        },
                        new
                        {
                            Id = 18,
                            DC = 16,
                            Description = @"When you drink this potion, it cures any disease afflicting you, and it removes the blinded, deafened, paralyzed, and poisoned conditions.
The clear red liquid has tiny bubbles of light in it. ",
                            PotionName = "Elixir of Health",
                            Rarity = 2
                        },
                        new
                        {
                            Id = 19,
                            DC = 16,
                            Description = @"When you drink this potion, you gain the effect of the Clairvoyance spell.
An eyeball bobs in this yellowish liquid but vanishes when the potion is opened.",
                            PotionName = "Potion of Clairvoyance",
                            Rarity = 2
                        },
                        new
                        {
                            Id = 20,
                            DC = 16,
                            Description = @"When you drink this potion, you gain the ""reduce"" effect of the enlarge/reduce spell for 1d4 hours (no Concentration required).
The red in the potion's liquid continuously contracts to a tiny bead and then expands to color the clear liquid around it. Shaking the bottle fails to interrupt this process.",
                            PotionName = "Potion of Diminution",
                            Rarity = 2
                        },
                        new
                        {
                            Id = 21,
                            DC = 16,
                            Description = @"When you drink this potion, you gain the effect of the Gaseous Form spell for 1 hour (no Concentration required) or until you end the effect as a Bonus Action.
This potion's container seems to hold fog that moves and pours like water.",
                            PotionName = "Potion of Gaseous Form",
                            Rarity = 2
                        },
                        new
                        {
                            Id = 22,
                            DC = 17,
                            Description = @"When you drink this potion, your Strength score changes to 23 for 1 hour. The potion has no effect on you if your Strength is equal to or greater than that score.
This potion's transparent liquid has floating in it a sliver of fingernail from a frost/stone giant.",
                            PotionName = "Potion of Giant Strength (Frost/Stone Giant)",
                            Rarity = 2
                        },
                        new
                        {
                            Id = 23,
                            DC = 18,
                            Description = @"When you drink this potion, your Strength score changes to 25 for 1 hour. The potion has no effect on you if your Strength is equal to or greater than that score.
This potion's transparent liquid has floating in it a sliver of fingernail from a fire giant.",
                            PotionName = "Potion of Giant Strength (Fire Giant)",
                            Rarity = 2
                        },
                        new
                        {
                            Id = 24,
                            DC = 17,
                            Description = @"For 1 hour after drinking it, you gain 10 Temporary Hit Points that last for 1 hour. For the same Duration, you are under the effect of the bless spell (no Concentration required).
This blue potion bubbles and steams as if boiling.",
                            PotionName = "Potion of Heroism",
                            Rarity = 2
                        },
                        new
                        {
                            Id = 25,
                            DC = 18,
                            Description = @"For 1 minute after you drink this potion, you have Resistance to all damage.
The potion's syrupy liquid looks like liquefied iron.",
                            PotionName = "Potion of Invulnerability",
                            Rarity = 2
                        },
                        new
                        {
                            Id = 26,
                            DC = 17,
                            Description = @"When you drink this potion, you gain the effect of the Detect Thoughts spell (save DC 13).
The potion's dense, purple liquid has an ovoid cloud of pink floating in it.",
                            PotionName = "Potion of Mind Reading",
                            Rarity = 2
                        },
                        new
                        {
                            Id = 27,
                            DC = 17,
                            Description = @"Beads of this cloudy gray oil form on the outside of its container and quickly evaporate.
The oil can cover a Medium or smaller creature, along with the Equipment it's wearing and carrying (one additional vial is required for each size category above Medium). Applying the oil takes 10 minutes. The affected creature then gains the effect of the Etherealness spell for 1 hour.",
                            PotionName = "Oil of Etherealness",
                            Rarity = 2
                        },
                        new
                        {
                            Id = 28,
                            DC = 20,
                            Description = @"You regain 10d4 + 20 Hit Points when you drink this potion. 
The potion's red liquid glimmers when agitated.",
                            PotionName = "Supreme Healing Potion",
                            Rarity = 3
                        },
                        new
                        {
                            Id = 29,
                            DC = 20,
                            Description = @"When you drink this potion, it removes any exhaustion you are suffering and cures any disease or poison affecting you. For the next 24 hours, you regain the maximum number of hit points for any Hit Die you spend.
The potion's crimson liquid regularly pulses with dull light, calling to mind a heartbeat. ",
                            PotionName = "Potion of Vitality",
                            Rarity = 3
                        },
                        new
                        {
                            Id = 30,
                            DC = 21,
                            Description = @"When you drink this potion, you gain a flying speed equal to your walking speed for 1 hour and can hover. If you're in the air when the potion wears off, you fall unless you have some other means of staying aloft.
This potion's clear liquid floats at the top of its container and has cloudy white impurities drifting in it.",
                            PotionName = "Potion of Flying",
                            Rarity = 3
                        },
                        new
                        {
                            Id = 31,
                            DC = 21,
                            Description = @"When you drink this potion, your Strength score changes to 27 for 1 hour. The potion has no effect on you if your Strength is equal to or greater than that score.
This potion's transparent liquid has floating in it a sliver of fingernail from a cloud giant.",
                            PotionName = "Potion of Giant Strength (Cloud Giant)",
                            Rarity = 3
                        },
                        new
                        {
                            Id = 32,
                            DC = 21,
                            Description = @"This potion's container looks empty but feels as though it holds liquid.
When you drink it, you become Invisible for 1 hour. Anything you wear or carry is Invisible with you. The effect ends early if you Attack or Cast a Spell.",
                            PotionName = "Potion of Invisibility",
                            Rarity = 3
                        },
                        new
                        {
                            Id = 33,
                            DC = 22,
                            Description = @"When you drink this potion, your physical age is reduced by 1d6 + 6 years, to a minimum of 13 years. Each time you subsequently drink a potion of longevity, there is 10 percent cumulative chance that you instead age by 1d6 + 6 years.
Suspended in this amber liquid are a scorpion's tail, an adder's fang, a dead spider, and a tiny heart that, against all reason, is still beating. These ingredients vanish when the potion is opened. ",
                            PotionName = "Potion of Longevity",
                            Rarity = 3
                        },
                        new
                        {
                            Id = 34,
                            DC = 21,
                            Description = @"When you drink this potion, you gain the effect of the haste spell for 1 minute (no Concentration required).
The potion’s yellow fluid is streaked with black and swirls on its own.",
                            PotionName = "Potion of Speed",
                            Rarity = 3
                        },
                        new
                        {
                            Id = 35,
                            DC = 21,
                            Description = @"This clear, gelatinous oil sparkles with tiny, ultrathin silver shards.
The oil can coat one slashing or piercing weapon or up to 5 pieces of slashing or piercing Ammunition. Applying the oil takes 1 minute. For 1 hour, the coated item is magical and has a +3 bonus to Attack and Damage Rolls.",
                            PotionName = "Oil of Sharpness",
                            Rarity = 3
                        },
                        new
                        {
                            Id = 36,
                            DC = 25,
                            Description = @"When you drink this potion, your Strength score changes to 29 for 1 hour. The potion has no effect on you if your Strength is equal to or greater than that score.
This potion's transparent liquid has floating in it a sliver of fingernail from a storm giant.",
                            PotionName = "Potion of Giant Strength (Storm Giant)",
                            Rarity = 3
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
